name: moviee-dev

services:
  backend_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: backend_dev
    ports:
      - "5005:5005"
    expose:
      - "8080"
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_FORWARD_HEADERS_STRATEGY=NATIVE
      - server.forward-headers-strategy=native
      # Enable remote debugging
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    env_file:
      - .env.dev
    networks:
      - moviee-network
    depends_on:
      db_dev:
        condition: service_healthy

  ngnix_dev:
    image: 'nginx:latest'
    container_name: ngnix_dev
    ports:
      - "443:443"
    volumes:
      - ./nginx-dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-dev/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx-dev/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - moviee-network
    depends_on:
      - backend_dev

  db_dev:
    image: 'postgres:17-alpine'
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: db_dev
    env_file:
      - .env.dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    command: [ "docker-entrypoint.sh",  "-c", "shared_buffers=256MB", "-c", "max_connections=200" ]
    expose:
      - 5432
    networks:
      - moviee-network
volumes:
  db-data:
networks:
  moviee-network:
    driver: bridge
